name: Test Antmicro Autoscaler

on:
  workflow_dispatch:

jobs:
  test-run:
    runs-on: [gha-runner-coordinator_0]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run a one-line script
      run: |
        echo "Hello, world! The time is $(date)."
