
name: test

on:
  workflow_dispatch:

jobs:
  centos:
    container: centos:7
    runs-on: [self-hosted, Linux, X64, gcp-custom-runners]
    env:
      GHA_SSH_TUNNEL_KEY: "${{ secrets.GHA_SSH_TUNNEL_KEY }}"
      GHA_SSH_TUNNEL_CONFIG: "${{ secrets.GHA_SSH_TUNNEL_CONFIG }}"
    steps:
    - run: yum -y install wget
    - run: wget http://localhost:8080 && cat index.html